runtime: python37

instance_class: F2

handlers:
- url: /(.+)
  static_files: www/\1
  upload: www/(.+)
  
- url: /
  static_files: www/home.html
  upload: www/home.html

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 100
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50